using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MareaGen
{
    /// <summary>
    /// Allows to MAREA the dynamic load of specific serialization and deserialization classes 
    /// generated by MAREAGen.
    /// </summary>
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
    public class InitializeOnLoadAttribute : Attribute
    {
        Type type;

        public InitializeOnLoadAttribute(Type type) { this.type = type; }

        public Type Type { get { return type; } }
    }
}
